server:
  address: 0.0.0.0
  port: 9091

jwt_secret: "CHANGE_ME"
session:
  secret: "CHANGE_ME"
  cookies:
    - name: authelia_session
      domain: ${DOMAIN}
      same_site: lax
storage:
  local:
    path: /config/db.sqlite3
identity_providers:
  oidc:
    hmac_secret: "CHANGE_ME"
    clients: []
access_control:
  default_policy: deny
  rules:
    - domain: "*.${DOMAIN}"
      policy: one_factor
