services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports: ["80:80", "443:443", "2019:2019"]
    environment:
      - TZ=${TZ}
    networks: [frontend, backend]
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DATA_DIR}/caddy/data:/data
      - ${DATA_DIR}/caddy/config:/config

  authelia:
    image: authelia/authelia:latest
    restart: unless-stopped
    networks: [backend]
    volumes:
      - ./config/authelia:/config
    environment:
      - TZ=${TZ}
networks:
  frontend:
    external: true
  backend:
    external: true
