# Plymouth script - minimal text
message_sprite = Sprite();
fun refresh() {
  Plymouth.SetDisplayNormal();
  Plymouth.SetBackgroundTopColor(0.0, 0.0, 0.0);
  Plymouth.SetBackgroundBottomColor(0.0, 0.0, 0.0);
  Plymouth.SetForegroundColor(255, 255, 255);
  message_sprite.SetX(0.1 * Window.GetWidth());
  message_sprite.SetY(0.8 * Window.GetHeight());
  message_sprite.SetText("SourceForge 2.0 is booting...");
}
refresh();
