services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    networks: [backend]
    env_file: [./env/mariadb.env]
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks: [backend]
    volumes:
      - redis-data:/data

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    restart: unless-stopped
    networks: [backend]
    env_file: [./env/minio.env]
    volumes:
      - minio-data:/data

  gitea:
    image: gitea/gitea:latest-rootless
    depends_on: [mariadb, redis]
    restart: unless-stopped
    networks: [frontend, backend]
    env_file: [./env/gitea.env]
    volumes:
      - gitea-data:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "${GITEA_SSH_PORT}:2222"

networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  gitea-data:
  mariadb-data:
  redis-data:
  minio-data:
