services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    networks: [frontend, backend]
    volumes:
      - uptime-data:/app/data
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  uptime-data:
