name: Build SourceForge 2.0 (from source via pi-gen, forced amd64 container)

on:
  workflow_dispatch:
    inputs:
      board:
        description: "Target board"
        required: true
        default: rpi234
        type: choice
        options:
          - rpi234
          - rpi5
  push:
    branches: [ main ]
    paths:
      - "overlay/**"
      - "os-pack/**"
      - "shell/**"
      - ".github/workflows/build-image.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set BOARD env (default rpi234)
        shell: bash
        run: |
          if [ -z "${{ github.event.inputs.board }}" ]; then
            echo "BOARD=rpi234" >> "$GITHUB_ENV"
          else
            echo "BOARD=${{ github.event.inputs.board }}" >> "$GITHUB_ENV"
          fi

      - name: Preflight - required files present
        shell: bash
        run: |
          set -e
          need=(
            overlay/usr/local/bin/sourceforge-term
            overlay/etc/systemd/system/sf20-terminal-tty1.service
            overlay/usr/local/sf20/first-boot.sh
            overlay/etc/profile.d/10-sf20-main.sh
            overlay/usr/share/plymouth/themes/sourceforge/sourceforge.plymouth
            overlay/usr/share/plymouth/themes/sourceforge/sourceforge.script
            os-pack/boot-side/sf20/sf20.repourl
          )
          miss=0
          for f in "${need[@]}"; do
            if [ ! -f "$f" ]; then echo "MISSING $f"; miss=1; else echo "ok      $f"; fi
          done
          if [ -d overlay/boot ]; then
            echo "ERROR overlay/boot must NOT exist; use os-pack/boot-side/" >&2
            exit 1
          fi
          [ "$miss" -eq 0 ]

      - name: Build sfsh (if sources exist)
        shell: bash
        run: |
          set -eux
          if [ -f shell/Makefile ] || [ -f shell/sfsh.c ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential
            make -C shell clean || true
            make -C shell
          else
            echo "No custom shell sources; sourceforge-term will fallback to /bin/bash -l"
          fi

      - name: Install host deps (docker + helpers)
        shell: bash
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y qemu-user-static debootstrap rsync xz-utils

      - name: Clone pi-gen
        shell: bash
        run: |
          set -eux
          git clone --depth 1 https://github.com/RPi-Distro/pi-gen.git

      # Force ARM64 build + sane mirror + no-check-gpg in config
      - name: Write pi-gen config
        shell: bash
        run: |
          set -eux
          cat > pi-gen/config <<'EOF'
          IMG_NAME=sf20
          TARGET_HOSTNAME=sf20
          ENABLE_SSH=1
          LOCALE_DEFAULT="en_US.UTF-8"
          KEYBOARD_KEYMAP="us"
          KEYBOARD_LAYOUT="English (US)"
          TIMEZONE_DEFAULT="UTC"

          # ARM64 rootfs target
          BUILD_ARM64=1
          STAGE_LIST="stage0 stage1 stage2"

          # Stable mirror
          APT_MIRROR=http://deb.debian.org/debian

          # Ensure stage0 doesn't choke on signatures in CI
          DEBOOTSTRAP_EXTRA_FLAGS="--no-check-gpg"

          SKIP_NOOBS=1
          EOF
          echo "== pi-gen/config =="
          cat pi-gen/config

      # Some pi-gen releases ignore DEBOOTSTRAP_EXTRA_FLAGS in stage0 ? hard patch it
      - name: Patch stage0 to always add --no-check-gpg
        shell: bash
        run: |
          set -eux
          STAGE0=pi-gen/stage0/prerun.sh
          if grep -q 'debootstrap ' "$STAGE0"; then
            sed -i 's@debootstrap @debootstrap --no-check-gpg @' "$STAGE0"
          fi
          head -n 120 "$STAGE0" || true

      - name: Create SF20 custom stage in pi-gen
        shell: bash
        run: |
          set -eux
          STAGE="pi-gen/stage2/99-sf20"
          mkdir -p "$STAGE/files/overlay" "$STAGE/00-run.chroot"

          # Root overlay into the image (pi-gen will rsync this)
          rsync -a overlay/ "$STAGE/files/overlay/"

          # Include custom shell if built
          if [ -f shell/sfsh ]; then
            install -m 0755 shell/sfsh "$STAGE/files/overlay/usr/local/bin/sfsh"
          fi

          # Chroot script to own TTY1, set root shell, banners, plymouth
          cat > "$STAGE/00-run.chroot/01-sf20-setup" <<'EOS'
          #!/bin/bash -e
          set -eux
          chmod +x /usr/local/bin/sourceforge-term || true
          [ -f /usr/local/bin/sfsh ] && chmod +x /usr/local/bin/sfsh || true

          systemctl disable getty@tty1.service || true
          ln -sf /dev/null /etc/systemd/system/getty@tty1.service || true
          systemctl enable sf20-terminal-tty1.service || true

          if [ -x /usr/local/bin/sfsh ]; then
            cp /etc/passwd /etc/passwd.sf20.bak
            awk -F: 'BEGIN{OFS=":"} $1=="root"{ $7="/usr/local/bin/sfsh" } {print }' /etc/passwd.sf20.bak > /etc/passwd.tmp
            mv /etc/passwd.tmp /etc/passwd
          fi

          echo "SourceForge 2.0 OS" > /etc/issue
          echo "SourceForge 2.0 OS" > /etc/issue.net

          if [ -f /usr/share/plymouth/themes/sourceforge/sourceforge.plymouth ]; then
            mkdir -p /etc/plymouth
            cat > /etc/plymouth/plymouthd.conf <<EOF
          [Daemon]
          Theme=sourceforge
          EOF
          fi
          EOS
          chmod +x "$STAGE/00-run.chroot/01-sf20-setup"

          # Export hook: copy boot-side content into BOOT FS during export
          EXP="pi-gen/export-image/99-sf20-boot"
          mkdir -p "$EXP/files/boot-side/sf20"
          rsync -a os-pack/boot-side/sf20/ "$EXP/files/boot-side/sf20/"
          cat > "$EXP/01-run.sh" <<'EOS'
          #!/bin/bash -e
          echo "[sf20] copying boot-side files into BOOTFS..."
          mkdir -p "$BOOTFS_DIR/sf20"
          rsync -rltD --no-perms --no-owner --no-group --modify-window=2 \
            "$PWD/99-sf20-boot/files/boot-side/sf20/" "$BOOTFS_DIR/sf20/" || true
          EOS
          chmod +x "$EXP/01-run.sh"

      # >>> Use our OWN Dockerfile so NO CHANCE of i386 base <<<
      - name: Write custom Dockerfile (bookworm, amd64)
        shell: bash
        run: |
          set -eux
          cat > pi-gen/Dockerfile.sf20 <<'DOCKER'
          FROM debian:bookworm

          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update && apt-get install -y --no-install-recommends \
                git ca-certificates xz-utils rsync \
                bc coreutils bzip2 zip unzip kmod udev cpio \
                debootstrap qemu-user-static parted kpartx dosfstools \
                curl wget gnupg dirmngr sudo jq \
              && rm -rf /var/lib/apt/lists/*

          WORKDIR /pi-gen
          # Copy the prepared pi-gen tree (with our config + patches)
          COPY . /pi-gen
          # Make sure scripts are executable
          RUN find /pi-gen -type f -name "*.sh" -exec chmod +x {} \; || true

          # Default command runs pi-gen inside the container
          CMD ["/bin/bash", "-lc", "./build.sh"]
          DOCKER

          echo "== Dockerfile.sf20 HEAD =="
          head -n 40 pi-gen/Dockerfile.sf20

      - name: Build pi-gen container (forced amd64)
        shell: bash
        env:
          DOCKER_DEFAULT_PLATFORM: linux/amd64
        run: |
          set -eux
          docker build --platform linux/amd64 -t sf20-pigen -f pi-gen/Dockerfile.sf20 pi-gen

      - name: Run pi-gen build in container
        shell: bash
        env:
          DOCKER_DEFAULT_PLATFORM: linux/amd64
        run: |
          set -eux
          # Run privileged (loop devices), mount deploy for artifacts
          docker run --privileged --rm \
            -e IMG_NAME=sf20 \
            -e BUILD_ARM64=1 \
            -e APT_MIRROR=http://deb.debian.org/debian \
            -e DEBOOTSTRAP_EXTRA_FLAGS="--no-check-gpg" \
            -v "$PWD/pi-gen/deploy":/pi-gen/deploy \
            sf20-pigen

      - name: Find built image
        id: findimg
        shell: bash
        run: |
          set -eux
          ls -lh pi-gen/deploy || true
          IMG="$(ls -1t pi-gen/deploy/*.img 2>/dev/null | head -n 1 || true)"
          if [ -z "$IMG" ]; then
            echo "No image found." >&2
            find pi-gen -maxdepth 2 -name build.log -print -exec tail -n 200 {} \;
            exit 1
          fi
          echo "img=$IMG" >> "$GITHUB_OUTPUT"
          ls -lh "$IMG"

      - name: Rename by board & compress
        shell: bash
        run: |
          set -eux
          SHORT="$BOARD"
          cp "${{ steps.findimg.outputs.img }}" "sf20-${SHORT}.img"
          xz -9v "sf20-${SHORT}.img"
          ls -lh "sf20-${SHORT}.img.xz"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sf20-${{ env.BOARD }}
          path: sf20-*.img.xz
          if-no-files-found: error
